CREATE TABLE `accountsPayableAdvanced` (
	`id` int AUTO_INCREMENT NOT NULL,
	`documentNumber` varchar(100),
	`description` varchar(255) NOT NULL,
	`supplierId` int,
	`purchaseOrderId` int,
	`unitId` int,
	`costCenterId` int,
	`category` enum('SUPPLIER','RENT','UTILITIES','SALARY','TAX','MARKETING','FREIGHT','SYSTEM','INSURANCE','MAINTENANCE','OTHER') NOT NULL DEFAULT 'OTHER',
	`amount` decimal(12,2) NOT NULL,
	`paidAmount` decimal(12,2) NOT NULL DEFAULT '0',
	`dueDate` timestamp NOT NULL,
	`paidDate` timestamp,
	`status` enum('PENDING','APPROVED','PARTIAL','PAID','OVERDUE','CANCELLED') NOT NULL DEFAULT 'PENDING',
	`approvalStatus` enum('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING',
	`approvedBy` int,
	`approvedAt` timestamp,
	`paymentMethod` enum('CASH','CREDIT','DEBIT','PIX','TRANSFER','CHECK','BOLETO'),
	`bankAccount` varchar(100),
	`isRecurring` boolean NOT NULL DEFAULT false,
	`recurringFrequency` enum('WEEKLY','MONTHLY','QUARTERLY','YEARLY'),
	`recurringEndDate` timestamp,
	`parentId` int,
	`installmentNumber` int,
	`totalInstallments` int,
	`notes` text,
	`attachments` json,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `accountsPayableAdvanced_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `accountsReceivableAdvanced` (
	`id` int AUTO_INCREMENT NOT NULL,
	`documentNumber` varchar(100),
	`description` varchar(255) NOT NULL,
	`customerId` int,
	`salesOrderId` int,
	`unitId` int,
	`amount` decimal(12,2) NOT NULL,
	`receivedAmount` decimal(12,2) NOT NULL DEFAULT '0',
	`dueDate` timestamp NOT NULL,
	`receivedDate` timestamp,
	`status` enum('PENDING','PARTIAL','RECEIVED','OVERDUE','CANCELLED','CHARGEBACK') NOT NULL DEFAULT 'PENDING',
	`paymentMethod` enum('CASH','CREDIT','DEBIT','PIX','TRANSFER','CHECK','BOLETO'),
	`cardBrand` varchar(50),
	`cardInstallments` int DEFAULT 1,
	`expectedReceiptDate` timestamp,
	`acquirerFee` decimal(10,2) DEFAULT '0',
	`netAmount` decimal(12,2),
	`bankAccount` varchar(100),
	`isReconciled` boolean NOT NULL DEFAULT false,
	`reconciledAt` timestamp,
	`reconciledBy` int,
	`chargebackReason` text,
	`notes` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `accountsReceivableAdvanced_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `auditLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`entityType` varchar(100) NOT NULL,
	`entityId` int NOT NULL,
	`action` enum('CREATE','UPDATE','DELETE','APPROVE','REJECT','CANCEL','ADJUST') NOT NULL,
	`fieldChanged` varchar(100),
	`oldValue` text,
	`newValue` text,
	`reason` text,
	`userId` int,
	`userName` varchar(255),
	`ipAddress` varchar(45),
	`userAgent` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `auditLogs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `bankReconciliation` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bankAccount` varchar(100) NOT NULL,
	`period` varchar(7) NOT NULL,
	`openingBalance` decimal(12,2) NOT NULL,
	`closingBalance` decimal(12,2) NOT NULL,
	`systemBalance` decimal(12,2) NOT NULL,
	`difference` decimal(12,2) NOT NULL,
	`status` enum('PENDING','IN_PROGRESS','RECONCILED','DISCREPANCY') NOT NULL DEFAULT 'PENDING',
	`reconciledBy` int,
	`reconciledAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bankReconciliation_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cashFlow` (
	`id` int AUTO_INCREMENT NOT NULL,
	`type` enum('INCOME','EXPENSE') NOT NULL,
	`category` enum('SALES','RECEIVABLES','OTHER_INCOME','SUPPLIERS','FREIGHT','SALARY','RENT','UTILITIES','MARKETING','TAX','FEES','OTHER_EXPENSE') NOT NULL,
	`subcategory` varchar(100),
	`description` varchar(255) NOT NULL,
	`amount` decimal(12,2) NOT NULL,
	`transactionDate` timestamp NOT NULL,
	`unitId` int,
	`costCenterId` int,
	`referenceId` int,
	`referenceType` varchar(50),
	`paymentMethod` enum('CASH','CREDIT','DEBIT','PIX','TRANSFER','CHECK','BOLETO'),
	`bankAccount` varchar(100),
	`isProjected` boolean NOT NULL DEFAULT false,
	`isReconciled` boolean NOT NULL DEFAULT false,
	`reconciledAt` timestamp,
	`notes` text,
	`userId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cashFlow_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cmvRecords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`period` varchar(7) NOT NULL,
	`unitId` int,
	`productId` int,
	`categoryId` int,
	`openingInventory` decimal(12,2) NOT NULL DEFAULT '0',
	`purchases` decimal(12,2) NOT NULL DEFAULT '0',
	`closingInventory` decimal(12,2) NOT NULL DEFAULT '0',
	`cmv` decimal(12,2) NOT NULL DEFAULT '0',
	`revenue` decimal(12,2) NOT NULL DEFAULT '0',
	`grossMargin` decimal(12,2) NOT NULL DEFAULT '0',
	`grossMarginPercent` decimal(5,2) NOT NULL DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cmvRecords_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `costCenters` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(50) NOT NULL,
	`name` varchar(255) NOT NULL,
	`type` enum('OPERATION','MARKETING','ADMINISTRATIVE','FINANCIAL','OTHER') NOT NULL,
	`description` text,
	`budget` decimal(12,2) DEFAULT '0',
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `costCenters_id` PRIMARY KEY(`id`),
	CONSTRAINT `costCenters_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `dreRecords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`period` varchar(7) NOT NULL,
	`unitId` int,
	`grossRevenue` decimal(14,2) NOT NULL DEFAULT '0',
	`returns` decimal(12,2) NOT NULL DEFAULT '0',
	`discounts` decimal(12,2) NOT NULL DEFAULT '0',
	`netRevenue` decimal(14,2) NOT NULL DEFAULT '0',
	`cmv` decimal(14,2) NOT NULL DEFAULT '0',
	`grossProfit` decimal(14,2) NOT NULL DEFAULT '0',
	`grossMarginPercent` decimal(5,2) NOT NULL DEFAULT '0',
	`salaryExpenses` decimal(12,2) NOT NULL DEFAULT '0',
	`rentExpenses` decimal(12,2) NOT NULL DEFAULT '0',
	`marketingExpenses` decimal(12,2) NOT NULL DEFAULT '0',
	`utilityExpenses` decimal(12,2) NOT NULL DEFAULT '0',
	`freightExpenses` decimal(12,2) NOT NULL DEFAULT '0',
	`otherExpenses` decimal(12,2) NOT NULL DEFAULT '0',
	`totalOperatingExpenses` decimal(14,2) NOT NULL DEFAULT '0',
	`operatingProfit` decimal(14,2) NOT NULL DEFAULT '0',
	`operatingMarginPercent` decimal(5,2) NOT NULL DEFAULT '0',
	`taxes` decimal(12,2) NOT NULL DEFAULT '0',
	`acquirerFees` decimal(12,2) NOT NULL DEFAULT '0',
	`otherFees` decimal(12,2) NOT NULL DEFAULT '0',
	`totalTaxesAndFees` decimal(12,2) NOT NULL DEFAULT '0',
	`netProfit` decimal(14,2) NOT NULL DEFAULT '0',
	`netMarginPercent` decimal(5,2) NOT NULL DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dreRecords_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pricingRules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`productId` int,
	`categoryId` int,
	`unitId` int,
	`baseCost` decimal(10,2),
	`taxRate` decimal(5,2) NOT NULL DEFAULT '0',
	`freightRate` decimal(5,2) NOT NULL DEFAULT '0',
	`commissionRate` decimal(5,2) NOT NULL DEFAULT '0',
	`marketplaceFee` decimal(5,2) NOT NULL DEFAULT '0',
	`acquirerFee` decimal(5,2) NOT NULL DEFAULT '0',
	`targetMargin` decimal(5,2) NOT NULL,
	`minMargin` decimal(5,2),
	`maxMargin` decimal(5,2),
	`suggestedPrice` decimal(10,2),
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pricingRules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `productCosts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`productId` int NOT NULL,
	`variantId` int,
	`unitId` int,
	`averageCost` decimal(10,4) NOT NULL,
	`lastPurchaseCost` decimal(10,2),
	`totalQuantity` int NOT NULL DEFAULT 0,
	`totalValue` decimal(12,2) NOT NULL DEFAULT '0',
	`lastUpdated` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `productCosts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `promotions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(50) NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`type` enum('PERCENTAGE','FIXED','BOGO','BUNDLE') NOT NULL,
	`discountValue` decimal(10,2) NOT NULL,
	`minPurchase` decimal(10,2),
	`maxDiscount` decimal(10,2),
	`productId` int,
	`categoryId` int,
	`unitId` int,
	`startDate` timestamp NOT NULL,
	`endDate` timestamp NOT NULL,
	`usageLimit` int,
	`usageCount` int NOT NULL DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`totalSales` decimal(14,2) NOT NULL DEFAULT '0',
	`totalDiscount` decimal(12,2) NOT NULL DEFAULT '0',
	`totalCMV` decimal(12,2) NOT NULL DEFAULT '0',
	`netProfit` decimal(12,2) NOT NULL DEFAULT '0',
	`roi` decimal(10,2) NOT NULL DEFAULT '0',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `promotions_id` PRIMARY KEY(`id`),
	CONSTRAINT `promotions_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `reconciliationItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`reconciliationId` int NOT NULL,
	`transactionDate` timestamp NOT NULL,
	`description` varchar(255) NOT NULL,
	`bankAmount` decimal(12,2) NOT NULL,
	`systemAmount` decimal(12,2),
	`difference` decimal(12,2),
	`status` enum('MATCHED','UNMATCHED','PENDING') NOT NULL DEFAULT 'PENDING',
	`cashFlowId` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `reconciliationItems_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `stockAnalysis` (
	`id` int AUTO_INCREMENT NOT NULL,
	`period` varchar(7) NOT NULL,
	`unitId` int,
	`productId` int NOT NULL,
	`categoryId` int,
	`abcClassRevenue` enum('A','B','C'),
	`abcClassProfit` enum('A','B','C'),
	`abcClassQuantity` enum('A','B','C'),
	`revenue` decimal(12,2) NOT NULL DEFAULT '0',
	`profit` decimal(12,2) NOT NULL DEFAULT '0',
	`quantitySold` int NOT NULL DEFAULT 0,
	`averageStock` decimal(10,2) NOT NULL DEFAULT '0',
	`stockValue` decimal(12,2) NOT NULL DEFAULT '0',
	`coverageDays` int NOT NULL DEFAULT 0,
	`turnoverRate` decimal(10,4) NOT NULL DEFAULT '0',
	`stockoutDays` int NOT NULL DEFAULT 0,
	`estimatedLostSales` decimal(12,2) NOT NULL DEFAULT '0',
	`idleCapital` decimal(12,2) NOT NULL DEFAULT '0',
	`idleDays` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `stockAnalysis_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `supplierHistory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`supplierId` int NOT NULL,
	`purchaseOrderId` int,
	`productId` int,
	`unitPrice` decimal(10,2) NOT NULL,
	`quantity` int NOT NULL,
	`totalValue` decimal(12,2) NOT NULL,
	`paymentTerms` varchar(100),
	`deliveryDays` int,
	`qualityRating` int,
	`deliveryRating` int,
	`notes` text,
	`purchaseDate` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `supplierHistory_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `unitPerformance` (
	`id` int AUTO_INCREMENT NOT NULL,
	`period` varchar(7) NOT NULL,
	`unitId` int NOT NULL,
	`grossRevenue` decimal(14,2) NOT NULL DEFAULT '0',
	`netRevenue` decimal(14,2) NOT NULL DEFAULT '0',
	`orderCount` int NOT NULL DEFAULT 0,
	`averageTicket` decimal(10,2) NOT NULL DEFAULT '0',
	`cmv` decimal(14,2) NOT NULL DEFAULT '0',
	`grossMargin` decimal(14,2) NOT NULL DEFAULT '0',
	`grossMarginPercent` decimal(5,2) NOT NULL DEFAULT '0',
	`totalExpenses` decimal(14,2) NOT NULL DEFAULT '0',
	`operatingProfit` decimal(14,2) NOT NULL DEFAULT '0',
	`netProfit` decimal(14,2) NOT NULL DEFAULT '0',
	`netMarginPercent` decimal(5,2) NOT NULL DEFAULT '0',
	`stockValue` decimal(14,2) NOT NULL DEFAULT '0',
	`stockTurnover` decimal(10,4) NOT NULL DEFAULT '0',
	`revenueRank` int,
	`profitRank` int,
	`marginRank` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `unitPerformance_id` PRIMARY KEY(`id`)
);
